global:
  scrape_interval: 15s

rule_files:
  - 'alerts.yml'

scrape_configs:
  - job_name: 'blackbox_http'
    scrape_timeout: 30s
    scrape_interval: 30s
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://google.com
        - # ... and so on
    relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: blackbox:9115

  - job_name: 'blackbox-icmp'
    scrape_interval: 30s
    scrape_timeout: 30s
    metrics_path: /probe
    params:
      module: ["icmp"]
    static_configs:
      - targets:
        - 1.1.1.1
        - # ... and so on
    relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: blackbox:9115